<h2>Création d'article</h2>
<form action="" method="post">
	<div class="row">
		<fieldset>
			<div class="form-group col-xs-6 col-sm-4 col-md-2">
				<label for="add_qty">Quantity</label>
				<input type="number" class="form-control" name="add_qty" value="1" min="1" max="<?php echo $item -> getStock() ?>">
			</div>
		</fieldset>
		<div class="submit col-xs-6 col-sm-4 col-md-2 text-right">
			<button type="submit" class="btn btn-primary">Add to cart</button>
		</div>
	</div>
</form>
		
<form role="form" method="post">
	<!--   ERREUR-->
    <div style="background-color:red;"><?=$errors?>
    </div>
    <input type="text" name="title" id="title" class="form-control input-sm" placeholder="title" value="<?=htmlentities($title)?>">
    <input type="text" name="content" id="content" class="form-control input-sm" placeholder="content" value="<?=htmlentities($content)?>">
    <input type="text" name="image" id="image" class="form-control input-sm" placeholder="image" value="<?=htmlentities($image)?>">

    <input type="submit" value="Enregistrer" class="btnLogin">
</form>