<!-- FORM -->
<form method="post" action="index.php?page=login">
<!-- TITRE -->
    <h2 class="h2Login">Identifiez vous</h2>
<!-- ERREURS -->
	<div style="background-color:red;"><?=$errors?></div>
<!-- LOGIN -->
    <label for="login">Login</label>
    <input type="text" id="login" name="login" placeholder="Login" required>
<!-- PASSWORD -->
    <label for="password">Mot de passe</label>
    <input type="password" id="password" name="password" placeholder="Password" required>
<!-- BUTTON -->
    <button class="btn" type="submit">Sign in</button>
  </form>