<div class="mentions">
	<h1>Mentions legales de ce site</h1>
	<h3>Propriétaire du site</h3>
	<p>Adrien Marchand / Hollux</p>
	<p>email : hollux@hotmail.fr</p>
	<br>
	<h3>Crédits</h3>
	<p>Développement : Hollux</p>
	<p>Webdesign : Hollux & <a href="solveig.portefoliobox.fr" target=_blank>Solveig De Cuyper</a></p>
	<br>
	<h3>Droits d'auteur</h3>
	<p>Le présent site constitue une œuvre de l'esprit au sens des dispositions des articles L 111-1 et suivants du Code de la Propriété Intellectuelle et, à ce titre, Hollux bénéficie en sa qualité d'auteur d'une protection et des droits réservés par la loi. A ce titre Hollux ne concède aucune de ses licences ni aucun autre droit que celui de consulter le site. Les noms et marques citées sont copyright de leurs auteurs respectifs.</p>
	<br>
	<h3>Conditions d'utilisation</h3>
	<p>L'utilisation de ce service est réservée à un usage strictement personnel et privé. Toute reproduction ou représentation partielle ou totale à d'autres fins sur un quelconque support est interdite, sauf autorisation expresse et préalable de Hollux en sa qualité d'auteur. Le non-respect de cette interdiction constitue une contrefaçon pouvant engager la responsabilité civile et pénale du contrefacteur à l'encontre duquel Hollux se réserve la possibilité de réclamer l'indemnisation de son entier préjudice.</p>
	<br>
	<h3>Hébergement du site</h3>
	<p>Le site www.hollux.fr est hébergé par la société OVH</p>
	<p>SAS au capital de 10 059 500 €</p>
	<p>RCS Lille Métropole 424 761 419 00045</p>
	<p>Code APE 6202A</p>
	<p>N° TVA : FR 22 424 761 419</p>
	<p>Siège social : 2 rue Kellermann - 59100 Roubaix - France</p>
	<p>Directeur de la publication : Octave KLABA</p>
</div>