<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.php">Hollux</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
<!--         <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
<li><a href="#">Link</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">-> Test <-<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <?php 
              if(!isset($_SESSION['id']))
              {
                echo('
                <li><a href="?page=register">Register</a></li>
                <li><a href="?page=login">Login</a></li>
                  ');
              }
             ?>
             <?php 
              if(isset($_SESSION['id']))
              {
                echo('
                  <li><a href="?page=logout">Logout</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="?page=rien">Rien</a></li>
                  <li><a href="?page=addArticle">Add Article</a></li>
                  <li><a href="?page=articles">Articles</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="?page=addCategory">Add Category</a></li>
                  <li><a href="?page=XcategorysX">Categorys</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#"><p>'.$_SESSION['privilege'].'</p></a></li>
                  ');
              }
              ?>
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <?php 
        if(isset($_SESSION['id']))
        {
          echo('<li class="active"><a href="?page=profil&id='.$_SESSION['id'].'">'.$currentUser->getLogin().'</a></li>');
        }
         ?>
        <!-- <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>