<form method="post">

	<div style="background-color:red;"><?=$errors?></div>
	
	<div class="form-group">
    <label for="title">Titre categorie : </label>
    <input type="text" name="title" class="form-control" id="title" placeholder="titre" value="<?=htmlentities($title)  ?>">
  </div>

  <div class="form-group">
    <label for="content">Contenu categorie : </label>
    <input type="text" name="content" class="form-control" id="content" placeholder="contenu" value="<?=htmlentities($content) ?>">
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
</form>